title = "Beng Tan"
baseURL = "https://bengtan.com/"
languageCode = "en-au"
themesDir = "node_modules"
theme = "hugo-clarity"

[params]
author = "Beng Tan"
description = "Beng Tan's personal blog where I write about software, tech, startups and random things."
introDescription = "Hi! I'm a freelance [software engineer](/resume). I write about software, tech, startups and random things."
introURL = false

dateFormat = "2 Jan 2006"
mainSections = ["post"]
since = 2021
mobileNavigation = "right"
showShare = false

logo = "/images/logo.png"
footerLogo = "/images/logo.png"
fallBackOgImage = "/images/logo.png"

ga_analytics = "G-VTEK0C8GRX"

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"

  [[menu.social]]
    name = "github"
    weight = 1
    url = "https://github.com/bengtan"
  [[menu.social]]
    name = "twitter"
    weight = 2
    url = "https://twitter.com/bengtanAU"
  [[menu.social]]
    name = "rss"
    weight = 4
    url = "index.xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
