baseURL = "http://bengtan.com/"
languageCode = "en-au"
title = "Beng Tan"
theme = "hugo-clarity"

[params]
author = "Beng Tan"
introDescription = "I'm a freelance software engineer. I write about software, tech, startups and random things."
dateFormat = "2 Jan 2006"
mainSections = ["post"]
since = 2021
mobileNavigation = "right"
showShare = false

logo = "/images/logo.png"
footerLogo = "/images/logo.png"

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"

  [[menu.social]]
    name = "github"
    weight = 1
    url = "https://github.com/bengtan"
  [[menu.social]]
    name = "twitter"
    weight = 2
    url = "https://twitter.com/bengtanAU"
  [[menu.social]]
    name = "rss"
    weight = 4
    url = "index.xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
